DROP TABLE IF EXISTS menu;


CREATE TABLE  menu (
    item_id INT AUTO_INCREMENT PRIMARY KEY,
    item_name VARCHAR(150) NOT NULL,
    category VARCHAR(100) NOT NULL,
    item_price DOUBLE NOT NULL
);




-- Sample items
INSERT INTO menu (item_name, category, item_price) VALUES
-- Momo
('C Momo', 'Momo', 90),
('Veg Momo', 'Momo', 80),
('Chicken Momo', 'Momo', 100),
('Steam Momo', 'Momo', 85),
('Fried Momo', 'Momo', 95),
('Cheese Momo', 'Momo', 110),
('Tandoori Chicken Momo', 'Momo', 120),
('Buff Momo', 'Momo', 100),
('Paneer Momo', 'Momo', 95),
('Corn & Cheese Momo', 'Momo', 100),
('Spinach Momo', 'Momo', 90),
('Tofu Momo', 'Momo', 105),
('Chocolate Momo', 'Momo', 85),
('Jhol Momo', 'Momo', 100),
('Green Momo (Herb Infused)', 'Momo', 95),
('Spicy Garlic Momo', 'Momo', 100),
('KurKure Momo', 'Momo', 110),
('Veg Cheese Burst Momo', 'Momo', 115),

-- Chowmein
('Mix Chowmein', 'Chowmein', 90),
('Egg Chowmein', 'Chowmein', 85),
('Veg Chowmein', 'Chowmein', 75),
('Schezwan Chowmein', 'Chowmein', 95),
('Chicken Hakka Noodles', 'Chowmein', 100),
('Veg Schezwan Chowmein', 'Chowmein', 90),
('Paneer Chowmein', 'Chowmein', 95),
('Chili Garlic Chowmein', 'Chowmein', 95),
('Spinach Noodles', 'Chowmein', 90),
('Paneer Noodles', 'Chowmein', 100),
('Mixed Veg Chowmein', 'Chowmein', 85),
('Butter Noodles', 'Chowmein', 90),
('Singapore Noodles', 'Chowmein', 105),
('Thai Spicy Chowmein', 'Chowmein', 110),
('Mushroom Chowmein', 'Chowmein', 95),
('Tofu Noodles', 'Chowmein', 100),
('Egg Schezwan Chowmein', 'Chowmein', 100),

-- Drinks
('Soft Drinks', 'Drinks', 50),
('Lemon Soda', 'Drinks', 40),
('Masala Chai', 'Drinks', 30),
('Cold Coffee', 'Drinks', 60),
('Iced Tea', 'Drinks', 55),
('Mango Lassi', 'Drinks', 65),
('Fresh Lime Soda', 'Drinks', 45),
('Mint Mojito', 'Drinks', 70),
('Water Bottle (1L)', 'Drinks', 20),
('Peach Iced Tea', 'Drinks', 60),
('Strawberry Shake', 'Drinks', 70),
('Chocolate Shake', 'Drinks', 80),
('Banana Shake', 'Drinks', 65),
('Sweet Lassi', 'Drinks', 60),
('Salted Lassi', 'Drinks', 55),
('Green Tea', 'Drinks', 35),
('Coconut Water', 'Drinks', 40),
('Black Coffee', 'Drinks', 45),
('Herbal Lemon Tea', 'Drinks', 50),

-- Rice
('Chicken Biryani', 'Rice', 120),
('Veg Biryani', 'Rice', 100),
('Jeera Rice', 'Rice', 70),
('Egg Fried Rice', 'Rice', 90),
('Chicken Fried Rice', 'Rice', 110),
('Veg Pulao', 'Rice', 85),
('Schezwan Fried Rice', 'Rice', 95),
('Paneer Fried Rice', 'Rice', 105),
('Chicken Schezwan Rice', 'Rice', 120),
('Tamarind Rice', 'Rice', 80),
('Lemon Rice', 'Rice', 75),
('Curd Rice', 'Rice', 70),
('Peas Pulao', 'Rice', 85),
('Hyderabadi Biryani', 'Rice', 140),
('Mutton Biryani', 'Rice', 180),
('Veg Handi Biryani', 'Rice', 120),
('Egg Biryani', 'Rice', 110),
('Soya Biryani', 'Rice', 100),
('Paneer Biryani', 'Rice', 130),

-- Starter
('Paneer Tikka', 'Starter', 150),
('Chicken Tikka', 'Starter', 160),
('Veg Spring Roll', 'Starter', 90),
('Malai Tikka', 'Starter', 170),
('Hara Bhara Kabab', 'Starter', 100),
('Fish Fingers', 'Starter', 160),
('Chili Paneer Dry', 'Starter', 140),
('Chicken Lollipop', 'Starter', 170),
('Stuffed Mushroom', 'Starter', 130),
('Tandoori Soya Chaap', 'Starter', 120),
('Paneer Malai Tikka', 'Starter', 160),
('Veg Seekh Kabab', 'Starter', 110),
('Dragon Chicken', 'Starter', 180),
('Crispy Corn', 'Starter', 110),
('Aloo 65', 'Starter', 90),
('Gobi Manchurian Dry', 'Starter', 100),

-- Main Course
('Paneer Butter Masala', 'Main Course', 180),
('Chicken Curry', 'Main Course', 200),
('Dal Makhani', 'Main Course', 140),
('Kadhai Paneer', 'Main Course', 160),
('Mutton Rogan Josh', 'Main Course', 250),
('Palak Paneer', 'Main Course', 170),
('Butter Chicken', 'Main Course', 220),
('Egg Curry', 'Main Course', 130),
('Paneer Do Pyaza', 'Main Course', 160),
('Methi Malai Matar', 'Main Course', 150),
('Chicken Masala', 'Main Course', 210),
('Rajma Masala', 'Main Course', 130),
('Chana Masala', 'Main Course', 120),
('Mutton Keema', 'Main Course', 240),
('Baingan Bharta', 'Main Course', 110),
('Mix Veg Curry', 'Main Course', 125),
('Kadhai Chicken', 'Main Course', 215),
('Shahi Paneer', 'Main Course', 180),

-- Bread
('Garlic Naan', 'Bread', 40),
('Butter Naan', 'Bread', 50),
('Tandoori Roti', 'Bread', 20),
('Lachha Paratha', 'Bread', 35),
('Butter Roti', 'Bread', 25),
('Stuffed Naan', 'Bread', 55),
('Plain Roti', 'Bread', 15),
('Missi Roti', 'Bread', 25),
('Naan with Stuffing', 'Bread', 60),
('Roomali Roti', 'Bread', 20),
('Cheese Naan', 'Bread', 65),
('Ajwain Paratha', 'Bread', 30),
('Methi Paratha', 'Bread', 30),
('Garlic Butter Naan', 'Bread', 55),
('Kulcha', 'Bread', 40),
('Tandoori Laccha Paratha', 'Bread', 45),

-- Dessert
('Gulab Jamun', 'Dessert', 60),
('Ice Cream', 'Dessert', 70),
('Rasgulla', 'Dessert', 50),
('Brownie with Ice Cream', 'Dessert', 90),
('Jalebi', 'Dessert', 40),
('Malpua with Rabri', 'Dessert', 75),
('Moong Dal Halwa', 'Dessert', 80),
('Gajar Ka Halwa', 'Dessert', 70),
('Sizzling Brownie', 'Dessert', 100),
('Falooda', 'Dessert', 85),
('Dry Fruit Kheer', 'Dessert', 65),
('Rasmalai', 'Dessert', 75),
('Kesari Bath', 'Dessert', 60),
('Fruit Custard', 'Dessert', 70),
('Kheer', 'Dessert', 55),
('Chocolate Mousse', 'Dessert', 85),
('Fruit Salad with Ice Cream', 'Dessert', 90),

-- Breakfast
('Aloo Paratha with Curd', 'Breakfast', 60),
('Idli Sambar', 'Breakfast', 50),
('Masala Dosa', 'Breakfast', 65),
('Upma', 'Breakfast', 40),
('Poha', 'Breakfast', 35),
('Chole Bhature', 'Breakfast', 70),
('Oats Porridge', 'Breakfast', 45),
('Puri Sabji', 'Breakfast', 60),
('Egg Bhurji with Toast', 'Breakfast', 70),
('Stuffed Veg Sandwich', 'Breakfast', 55),

-- Snacks
('Samosa', 'Snacks', 20),
('Kachori', 'Snacks', 25),
('Bread Pakora', 'Snacks', 30),
('Aloo Tikki', 'Snacks', 35),
('Vegetable Cutlet', 'Snacks', 40),
('Onion Rings', 'Snacks', 50),
('Paneer Popcorn', 'Snacks', 60),
('French Fries', 'Snacks', 50),
('Maggi', 'Snacks', 40),
('Cheese Corn Balls', 'Snacks', 70),

-- Pizza
('Margherita Pizza', 'Pizza', 150),
('Farmhouse Pizza', 'Pizza', 180),
('Paneer Tikka Pizza', 'Pizza', 190),
('Chicken BBQ Pizza', 'Pizza', 220),
('Pepperoni Pizza', 'Pizza', 230),
('Cheese Burst Pizza', 'Pizza', 200),
('Veggie Delight Pizza', 'Pizza', 170),
('Mushroom Pizza', 'Pizza', 185),
('Four Cheese Pizza', 'Pizza', 210),
('Spicy Mexican Pizza', 'Pizza', 195),

-- Pasta
('White Sauce Pasta', 'Pasta', 160),
('Red Sauce Pasta', 'Pasta', 150),
('Arrabiata Pasta', 'Pasta', 155),
('Cheesy Garlic Pasta', 'Pasta', 170),
('Spaghetti Aglio e Olio', 'Pasta', 180),
('Mac & Cheese', 'Pasta', 165),
('Chicken Alfredo Pasta', 'Pasta', 200),
('Penne with Veggies', 'Pasta', 160),
('Spinach & Corn Pasta', 'Pasta', 170),
('Mushroom Cream Pasta', 'Pasta', 175),

-- South Indian
('Plain Dosa', 'South Indian', 50),
('Masala Dosa', 'South Indian', 65),
('Onion Uttapam', 'South Indian', 60),
('Rava Dosa', 'South Indian', 70),
('Medu Vada', 'South Indian', 45),
('Pongal', 'South Indian', 55),
('Set Dosa', 'South Indian', 50),
('Vegetable Upma', 'South Indian', 40),
('Coconut Rice', 'South Indian', 70),
('Lemon Sevai', 'South Indian', 60),

-- Vegan
('Vegan Buddha Bowl', 'Vegan', 180),
('Tofu Stir Fry', 'Vegan', 170),
('Chickpea Salad', 'Vegan', 140),
('Vegan Burrito', 'Vegan', 160),
('Vegan Thai Curry', 'Vegan', 190),
('Grilled Veg Wrap', 'Vegan', 150),
('Avocado Toast', 'Vegan', 130),
('Vegan Smoothie Bowl', 'Vegan', 120),
('Hummus with Pita', 'Vegan', 110),
('Lentil Soup', 'Vegan', 100),

-- Chinese
('Veg Manchurian Gravy', 'Chinese', 120),
('Chicken Manchurian', 'Chinese', 150),
('Chili Garlic Noodles', 'Chinese', 100),
('Hakka Noodles', 'Chinese', 95),
('Schezwan Noodles', 'Chinese', 110),
('Sweet Corn Soup', 'Chinese', 80),
('Hot & Sour Soup', 'Chinese', 85),
('Spring Roll', 'Chinese', 90),
('Veg Fried Wontons', 'Chinese', 100),
('Schezwan Paneer', 'Chinese', 140);

